output "k8s_auth_backend_path" {
  description = "The path where Kubernetes auth backend is mounted"
  value       = module.terraform-vault-kubernetes.k8s_auth_backend_path
}

output "k8s_auth_backend_config" {
  description = "Configuration of the Kubernetes auth backend"
  sensitive   = true
  value       = module.terraform-vault-kubernetes.k8s_auth_backend_config
}

output "k8s_role_name" {
  description = "The name of the Kubernetes auth backend role"
  value       = module.terraform-vault-kubernetes.k8s_role_name
}

output "k8s_role_bound_service_account_names" {
  description = "The bound service account names for the Kubernetes auth backend role"
  value       = module.terraform-vault-kubernetes.k8s_role_bound_service_account_names
}

output "k8s_role_bound_service_account_namespaces" {
  description = "The bound service account namespaces for the Kubernetes auth backend role"
  value       = module.terraform-vault-kubernetes.k8s_role_bound_service_account_namespaces
}

output "k8s_role_token_ttl" {
  description = "The TTL for tokens generated by the Kubernetes auth backend role"
  value       = module.terraform-vault-kubernetes.k8s_role_token_ttl
}

output "k8s_role_token_policies" {
  description = "The policies attached to tokens generated by the Kubernetes auth backend role"
  value       = module.terraform-vault-kubernetes.k8s_role_token_policies
}
