output "k8s_auth_backend_path" {
  description = "The path where Kubernetes auth backend is mounted"
  value       = vault_auth_backend.kubernetes.path
}

output "k8s_auth_backend_config" {
  description = "Configuration of the Kubernetes auth backend"
  sensitive   = true
  value       = vault_kubernetes_auth_backend_config.k8s_auth
}

output "k8s_role_name" {
  description = "The name of the Kubernetes auth backend role"
  value       = vault_kubernetes_auth_backend_role.k8s_role.role_name
}

output "k8s_role_bound_service_account_names" {
  description = "The bound service account names for the Kubernetes auth backend role"
  value       = vault_kubernetes_auth_backend_role.k8s_role.bound_service_account_names
}

output "k8s_role_bound_service_account_namespaces" {
  description = "The bound service account namespaces for the Kubernetes auth backend role"
  value       = vault_kubernetes_auth_backend_role.k8s_role.bound_service_account_namespaces
}

output "k8s_role_token_ttl" {
  description = "The TTL for tokens generated by the Kubernetes auth backend role"
  value       = vault_kubernetes_auth_backend_role.k8s_role.token_ttl
}

output "k8s_role_token_policies" {
  description = "The policies attached to tokens generated by the Kubernetes auth backend role"
  value       = vault_kubernetes_auth_backend_role.k8s_role.token_policies
}
