install-tools:
    stage: .pre
    script:
        # Vault CLI
        - apt update && apt install -y unzip jq
        - wget https://releases.hashicorp.com/vault/1.8.4/vault_1.8.4_linux_arm64.zip
        - unzip vault_1.8.4_linux_arm64.zip
        - mv vault /usr/bin
        - which vault
    tags:
        - my_laptop

build-the-thing:
    stage: build
    script:
        - export VAULT_ADDR=http://host.docker.internal:8200
        
        # Get a Vault token using the GitLab JWT
        - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=gitlab-runner jwt=$CI_JOB_JWT)"
        
        # Get a secret using the Vault CLI
        - export SECRET=$(vault read -format=json aws/creds/gitlab-runner)
        - export AWS_ACCESS_KEY_ID=$(echo $SECRET | jq -r .data.access_key)
        - export AWS_SECRET_KEY=$(echo $SECRET | jq -r .data.secret_key)
        
        - echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - echo AWS_SECRET_KEY=$AWS_SECRET_KEY
    tags:
        - my_laptop
